version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: hackathon
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: car-fleet-app
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://hackathon:1234@postgres:5432/mydb
    depends_on:
      - postgres

volumes:
  postgres_data:
    driver: local
